import type { Metadata } from "next";
import { Phudu } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const phudu = Phudu({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className= {`${phudu.className} lg:mx-12 lg:py-8 px-6 lg:px-0 overflow-x-hidden `} >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
